name: lingo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  fl_chart: ^0.69.0
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  flutter_tts: ^4.2.0
  google_fonts: 6.3.2
  flutter_local_notifications: ^18.0.1
  intl: ^0.19.0
  flutter_svg: ^2.0.0
  shared_preferences: ^2.2.2
  web_socket_channel: ^3.0.3
  permission_handler: ^11.3.0

  # Microphone (Works on Android/iOS)


  # Crypto + utils
  crypto: ^3.0.2

  # REQUIRED for Gemini (1.x only)
  http_parser: ^4.0.2

  # GEMINI TRANSLATION API ❤️
  google_generative_ai: 0.4.6
  http: 1.6.0
  
  # Animations
  confetti: ^0.7.0
  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/invite.png
    - assets/illustrations/
